inherit_gem:
  bixby: bixby_default.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
