require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
  Metrics/BlockLength:
    Exclude:
      - 'spec/**/*.rb'
  Style/FrozenStringLiteralComment:
    Exclude:
      - 'db/migrate/**/*.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

# Sure, it's nice in theory to have one expectation per spec, but that can
# result in slower test suites as you perform significant setup for each spec.
RSpec/MultipleExpectations:
  Enabled: false
