##
# At the moment, we are running our cypress commands outside of the docker container. The version of @esbuild that we need locally on MacOS is different than the version needed inside the Docker container, which runs on Linux. In order to allow both versions to exist, while still being able to run the app with Vite, we need to add the following to our .yarnrc.yml file:
# ref: https://esbuild.github.io/getting-started/#simultaneous-platforms
# ref: https://yarnpkg.com/configuration/yarnrc#supportedArchitectures
supportedArchitectures: {
  os: [
    'current',
    'darwin',
    'linux',
  ],
  cpu: [
    'current',
    'x64',
  ]
}
