version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}

  web:
    build:
      context: .
      target: viva-base
    image: ghcr.io/scientist-softserv/viva:${TAG:-latest}
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/viva
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres: