version: '3.8'

x-app: &app
  build:
    context: .
    target: viva-base
  image: ghcr.io/scientist-softserv/viva:${TAG:-latest}
  volumes:
    - .:/app
  env_file:
    - .env
    - .env.development
  # Keep the stdin open, so we can attach to our app container's process
  # and do things such as byebug, etc:
  stdin_open: true
  # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
  tty: true

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_HOST=${DATABASE_HOST}
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  vite:
    <<: *app
    entrypoint: /bin/bash ./ops/entrypoint-vite.sh
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    ports:
      - "3036:3036"

  web:
    <<: *app
    command: bash -c "bundle exec puma -p 3000"
    ports:
      - 3000
    depends_on:
      - postgres
      - vite
    environment:
      VIRTUAL_HOST: viva.test
      VIRTUAL_PORT: 3000
      VITE_RUBY_HOST: vite

volumes:
  postgres:
