{{- if .Values.ingress.enabled -}}
apiVersion: {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
  networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
  networking.k8s.io/v1beta1
{{- else -}}
  extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "chart.fullname" . }}-in
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: {{ include "chart.fullname" . }}
              servicePort: {{ .Values.service.port }}
    {{- end }}
{{- end }}
