apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viva-pvc-shared
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.shared.storage.size }}
  storageClassName: {{ .Values.shared.storage.className }}
