default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: viva_development

test:
  <<: *default
  database: viva_test

production:
  <<: *default
  database: viva_production
  username: viva
  password: <%= ENV["VIVA_DATABASE_PASSWORD"] %>
