subjects:
  name:
    - 'Applied Science'
    - 'Arts and Humanities'
    - 'Business and Communication'
    - 'Career and Technical Education'
    - 'Education'
    - 'Engineering'
    - 'English Language Arts'
    - 'Health Sciences'
    - 'History'
    - 'Law'
    - 'Life Science'
    - 'Mathematics'
    - 'Physical Science'
    - 'Social Science'