name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: notch8/actions/.github/workflows/build.yaml@v0.0.23
    secrets: inherit
    with:
      platforms: 'linux/amd64'
      webTarget: viva-base
  rspec-tests:
    needs: build
    uses: notch8/actions/.github/workflows/test.yaml@v0.0.23
  reports:
    needs: rspec-tests
    uses: notch8/actions/.github/workflows/report.yaml@v0.0.23
  cypress-tests:
    needs: build
    uses: notch8/actions/.github/workflows/cypress.yaml@update-cypress-yaml
    with:
      cypress-container-name: cypress-tests
  rubocop:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@v0.0.23
  eslint:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@v0.0.23
    with:
      rubocop_cmd: yarn && yarn lint:all
