name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v0.0.13
    secrets: inherit
    with:
      platforms: 'linux/amd64'
      target: viva-base
  rspec-tests:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.13
  cypress-chrome-tests:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.13
    with:
      rspec_cmd: exit && docker-compose exec -T viva-cypress-components-on-chrome-1 sh -c "yarn cypress:run:chrome"
  cypress-firefox-tests:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.13
    with:
      rspec_cmd: exit && docker-compose exec -T viva-cypress-components-on-chrome-1 sh -c "yarn cypress:run:firefox"
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.13
