name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@v0.0.17
    secrets: inherit
    with:
      platforms: 'linux/amd64'
      target: viva-base
  rspec-tests:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@seperate_reports
  reports:
    needs: rspec-tests
    uses: scientist-softserv/actions/.github/workflows/report.yaml@seperate_reports
  cypress-tests:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/cypress.yaml@v0.0.17
    with:
      cypress-container-name: cypress-tests
  rubocop:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.17
  eslint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.17
    with:
      lint_cmd: docker-compose run web -- bash -c 'yarn && yarn lint:all'
